### ISSUE TITLE
Does it works with blue print??

### ISSUE THREAD

**Issue by llPekoll** [italomaia/flask-rev#2] opened 2019-12-14 14:37 UTC
I do have multiple blueprints
and it doesn't seem to work

```
group = Blueprint("group", __name__, static_url_path='/datas/cards_group',
                  static_folder='/datas/cards_group')
```
and some other blueprint
```
account = Blueprint("account", __name__, static_url_path='/datas/cards',
                  static_folder='/datas/cards')
```
and it doesn't seems to make the connection properly 
```
{{ url_for('group.static',filename=img) }
{{ url_for('account.static',filename=img) }
```
for both of them I'll have the same path

**Comment by italomaia** [comment] 2019-12-14 20:27
Lemme check ...

**Comment by italomaia** [comment] 2019-12-14 23:12
Hello @llPekoll I just added an example to flask-rev. Would you be able to fork the project and modify the example so I can see what you mean? I tested here and it worked normally.

**Comment by italomaia** [comment] 2019-12-20 16:40
Closing as I cannot reproduce the issue. Please, feel free to re-open it if you manage to create a example showing the problem.

**Closed as completed by italomaia** 2019-12-20 16:40 UTC

**Comment by llPekoll** [comment] 2019-12-23 07:06
My bad it's working on a simple sample,
I'll investigate more on my setup thanks for the reply anyway :)

**Comment by llPekoll** [comment] 2019-12-23 07:37
but did you changed anything?
It use to return me an exception on my project, now it just does nothing, 
Just want to know my be from my side again
sorry to disturb : innocent:

**Comment by llPekoll** [comment] 2019-12-23 11:23
I found my issue
<img width="1376" alt="Screen Shot 2019-12-23 at 12 14 14" src="https://user-images.githubusercontent.com/12329162/71355094-414e9f00-257e-11ea-858c-4fb154bf52a4.png">
as you can see in the console in the bottom, this one wasn't working since I've registered the static at the origin of the flask app(on the left), and I used  just 'static'
I have created another blueprint to register my path so I can call 'base.static' as you can see on the second screenshot
<img width="1345" alt="Screen Shot 2019-12-23 at 12 20 33" src="https://user-images.githubusercontent.com/12329162/71355260-c20d9b00-257e-11ea-8dcc-14e8ab30c218.png">
I have now a proper return,
Thanks a lot for the Tool tho :heart_eyes:
